// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6mkuF4d2SouPvE8m4gAhqLIfVYaA4BI',
    appId: '1:1095144756055:web:81c1a4e38b6b72528d6412',
    messagingSenderId: '1095144756055',
    projectId: 'prayana-ev',
    authDomain: 'prayana-ev.firebaseapp.com',
    databaseURL: 'https://prayana-ev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prayana-ev.appspot.com',
    measurementId: 'G-5XQ8BS6GD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKuRTvGVE4y71sMfIi8lcxrkm4xdP1SY',
    appId: '1:1095144756055:android:5f9f2f2d47340c6e8d6412',
    messagingSenderId: '1095144756055',
    projectId: 'prayana-ev',
    databaseURL: 'https://prayana-ev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prayana-ev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmNfLDrA3FNz2WC_B1HWCdd17Id5IT27s',
    appId: '1:1095144756055:ios:cb3d4c1c58e73cba8d6412',
    messagingSenderId: '1095144756055',
    projectId: 'prayana-ev',
    databaseURL: 'https://prayana-ev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prayana-ev.appspot.com',
    iosBundleId: 'com.example.prayanaev.prayanaev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmNfLDrA3FNz2WC_B1HWCdd17Id5IT27s',
    appId: '1:1095144756055:ios:0a9a64dca0bb827e8d6412',
    messagingSenderId: '1095144756055',
    projectId: 'prayana-ev',
    databaseURL: 'https://prayana-ev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prayana-ev.appspot.com',
    iosBundleId: 'com.example.prayanaev.prayanaev.RunnerTests',
  );
}
